services:
  postgres:
    image: postgres:16-alpine
    container_name: payment-lab-postgres
    environment:
      POSTGRES_DB: payment_lab
      POSTGRES_USER: payment_lab
      POSTGRES_PASSWORD: payment_lab
    ports:
      - "5433:5432"
    volumes:
      - payment_lab_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_lab -d payment_lab"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  payment_lab_postgres_data:
