spring:
  application:
    name: payment-lab
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/payment_lab}
    username: ${DB_USERNAME:payment_lab}
    password: ${DB_PASSWORD:payment_lab}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
