spring:
  application:
    name: payment-lab
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s
          multiplier: 1
          max-interval: 2s
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/payment_lab}
    username: ${DB_USERNAME:payment_lab}
    password: ${DB_PASSWORD:payment_lab}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

logging:
  file:
    path: ${LOG_DIR:${LOG_ROOT:/home/juaneugenio/programmig/java-senior-labs/logs}/payment-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
